### ISSUE TITLE
ensure that logs don't span more than 24 hours

### ISSUE THREAD

**Issue by afeld** [GSA/mysql_to_cloudwatch#15]
```
Uploading 3 events...
Traceback (most recent call last):
  File "run.py", line 27, in <module>
    integration.run(db, cw)
  File "/usr/src/app/src/integration.py", line 16, in run
    copy_new_general_logs(db, cw)
  File "/usr/src/app/src/integration.py", line 12, in copy_new_general_logs
    cw.upload_logs(events)
  File "/usr/src/app/src/cloudwatch.py", line 72, in upload_logs
    self.client.put_log_events(**log_args)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 253, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 543, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the PutLogEvents operation: The batch of log events in a single PutLogEvents request cannot span more than 24 hours.
```

which is consistent with the constraint listed in [the API documentation](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html).

**Comment by afeld** [comment]
Part of #7.
